POST http://0.0.0.0:9000/register
Content-Type: application/json

{
  "username": "newTest",
  "email": "email200@test.ru",
  "password": "qwerty"
}

###
POST http://localhost:9000/auth
Content-Type: application/json

{
  "email": "email@test.ru",
  "password": "qwerty"
}

###

POST http://localhost:9000/logout
Authorization: Bearer ea11f4a7-c906-438a-b444-61dbab08927f

###

POST http://localhost:9000/chats/create
Content-Type: application/json
Authorization: Bearer ea11f4a7-c906-438a-b444-61dbab08927f

{
  "title": "room name",
  "encodedImage": "base64 string"
}

###

GET http://localhost:9000/chats/list

###

GET http://localhost:9000/chats/find/1

###

GET http://localhost:9000/chats/find?title=name

###

GET http://localhost:9000/rooms/list
Authorization: Bearer 457370b2-2320-45c6-94af-99df3b9d452c

###
PUT http://localhost:9000/rooms/join/5
Authorization: Bearer 457370b2-2320-45c6-94af-99df3b9d452c

###
PUT http://localhost:9000/rooms/leave/5
Authorization: Bearer 457370b2-2320-45c6-94af-99df3b9d452c

###

GET http://localhost:9000/rooms/list/users/5
Authorization: Bearer 457370b2-2320-45c6-94af-99df3b9d452c

###

POST http://localhost:9000/user/image
Content-Type: application/json
Authorization: Bearer 457370b2-2320-45c6-94af-99df3b9d452c

{
  "encodedImage": "base64 string"
}

###

POST http://localhost:9000/rooms/image/5
Content-Type: application/json
Authorization: Bearer 457370b2-2320-45c6-94af-99df3b9d452c

{
  "encodedImage": "base64 string"
}

###

GET http://localhost:9000/user/1

###

POST http://localhost:9000/user/update
Content-Type: application/json
Authorization: Bearer 457370b2-2320-45c6-94af-99df3b9d452c

{
  "username": "newName",
  "password": "newPassword",
  "email": "newEmail",
  "image": {
    "encodedImage": "base64 string",
    "setDefaultImage": false
  }
}