POST http://0.0.0.0:9000/register
Content-Type: application/json

{
  "username": "test1",
  "email": "email@test.ru",
  "password": "qwerty"
}

###
POST http://localhost:9000/auth
Content-Type: application/json

{
  "email": "email@test.ru",
  "password": "qwerty"
}
