POST http://0.0.0.0:9000/register
Content-Type: application/json

{
  "username": "test1",
  "email": "email@test.ru",
  "password": "qwerty"
}

###
POST http://localhost:9000/auth
Content-Type: application/json

{
  "email": "email@test.ru",
  "password": "qwerty"
}

###

POST http://localhost:9000/logout

###

POST http://localhost:9000/chats/create
Content-Type: application/json

{
  "title": "room name",
  "encodedImage": "base64 string"
}

###

GET http://localhost:9000/chats/list

###

GET http://localhost:9000/chats/find/1

###

GET http://localhost:9000/chats/find?title=name
